#!/usr/bin/env bash
echo "Run this command as sudo.";
sudo pip3 install -r requirements.txt;
sudo cp downloader.py /usr/bin/;
sudo chmod 777 /usr/bin/downloader.py;
sudo echo "alias youtube='python3 /usr/bin/downloader.py --dir ~/Downloads/Youtube'" >> ~/.bashrc;
echo "#####################################################";
echo "Youtube Video Downloader successfully installed";
echo "type 'youtube' from anywhere in terminal to launch the application";
