#!/usr/bin/env bash
echo "Run this command as sudo.";
sudo pip3 install -r requirements.txt;
sudo cp downloader.py /usr/bin/youtube;
sudo chmod 755 /usr/bin/youtube;
echo "#####################################################";
echo "Youtube Video Downloader successfully installed";
echo "type 'youtube' from anywhere in terminal to launch the application";
